# Generated by Django 5.0.6 on 2026-09-29 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doping_tests', '0001_initial'),
        ('laboratories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('sample_type', models.CharField(choices=[('URINE', 'Urine'), ('BLOOD', 'Blood'), ('OTHER', 'Other')], default='URINE', max_length=20)),
                ('collection_date', models.DateField()),
                ('collection_time', models.TimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('SUBMITTED', 'Submitted'), ('RECEIVED', 'Received'), ('UNDER_ANALYSIS', 'Under Analysis'), ('ANALYZED', 'Analyzed'), ('INVALID', 'Invalid')], default='COLLECTED', max_length=20)),
                ('chain_of_custody_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_samples', to=settings.AUTH_USER_MODEL)),
                ('doping_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='doping_tests.dopingtest')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_samples', to='laboratories.laboratorystaff')),
            ],
            options={
                'db_table': 'samples',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='samples_status_cce5be_idx'), models.Index(fields=['doping_test'], name='samples_doping__75b8e6_idx')],
            },
        ),
    ]
