# Generated by Django 5.0.6 on 2026-09-29 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('report_type', models.CharField(choices=[('TESTING_STATISTICS', 'Testing Statistics'), ('RESULT_STATISTICS', 'Result Statistics'), ('VIOLATION_STATISTICS', 'Violation Statistics'), ('LABORATORY_STATISTICS', 'Laboratory Statistics'), ('ATHLETE_HISTORY', 'Athlete History'), ('MONTHLY_SUMMARY', 'Monthly Summary')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
