# Generated by Django 5.0.6 on 2026-09-29 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DopingTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('test_type', models.CharField(choices=[('IN_COMPETITION', 'In-Competition'), ('OUT_OF_COMPETITION', 'Out-of-Competition'), ('TARGETED', 'Targeted'), ('FOLLOW_UP', 'Follow-up')], default='IN_COMPETITION', max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('SAMPLE_SUBMITTED', 'Sample Submitted'), ('UNDER_ANALYSIS', 'Under Analysis'), ('RESULT_GENERATED', 'Result Generated'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='athletes.athlete')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='officers.dopingcontrolofficer')),
            ],
            options={
                'db_table': 'doping_tests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='doping_test_status_394524_idx'), models.Index(fields=['athlete'], name='doping_test_athlete_2900f2_idx'), models.Index(fields=['officer'], name='doping_test_officer_7395d1_idx')],
            },
        ),
    ]
